#!/bin/bash
# cleanup.sh - Remove runtime artifacts from 04-aiida examples
#
# Restores the directory to its freshly-cloned state by removing files
# generated when the AiiDA examples are run:
#   **/<PK>.dot.png               (provenance graph PNGs from verdi node graph generate --output-format png)
#   **/<PK>.dot.pdf               (provenance graph PDFs from verdi node graph generate)
#   **/*.aiida                    (provenance archives from verdi archive create)
#   **/__pycache__/               (Python bytecode caches)
#
# Note: The AiiDA profile itself (~/.aiida/) is stored outside this directory
# and is not affected by this script.

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

# Provenance graphs generated by: verdi node graph generate <PK>
find "$SCRIPT_DIR" -name '*.dot.pdf' -type f -delete
find "$SCRIPT_DIR" -name '*.dot.png' -type f -delete

# Provenance archives generated by: verdi archive create --all <name>.aiida
find "$SCRIPT_DIR" -name '*.aiida' -type f -delete

# Python bytecode caches
find "$SCRIPT_DIR" -name '__pycache__' -type d -exec rm -rf {} +

echo "04-aiida cleaned."
